name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.1
  - python=3.8.8
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-DESeq2
  - r-RColorBrewer
  - r-ggrepel
  - r-scales
  - r-genefilter
  - r-pheatmap
  - r-ggbeeswarm
  - r-apeglm
  - r-qvalue
  - r-pcaExplorer
  - r-AnnotationDbi
  - r-DOSE
  - r-enrichplot
  - r-pathview
  - r-clusterProfiler
  - pip
  - pip:
    - pandas
    - matplotlib
    - numpy
